### PR TITLE
Add keyPassphrase option to signer

### LINKED ISSUE #81: Will not parse pem files that have a passphrase - solution offered
I was trying to parse a passphrase that was encrypted using a password. When I tried passing in the passphrase attribute in with the rest of the other options, I still got the same error:

```
/Users/jdavies/getObj/node_modules/sshpk/lib/private-key.js:192
			throw (e);
			^
KeyEncryptedError: The PEM format key (unnamed) is encrypted (password-protected), and no passphrase was provided in `options`
    at Object.read (/Users/jdavies/getObj/node_modules/sshpk/lib/formats/pem.js:75:12)
    at Object.read (/Users/jdavies/getObj/node_modules/sshpk/lib/formats/auto.js:24:16)
    at Object.PrivateKey.parse [as parsePrivateKey] (/Users/jdavies/getObj/node_modules/sshpk/lib/private-key.js:185:27)
    at Object.signRequest (/Users/jdavies/getObj/node_modules/http-signature/lib/signer.js:362:21)
    at sign (/Users/jdavies/getObj/getObj.js:61:19)
    at getUser (/Users/jdavies/getObj/getObj.js:99:5)
    at Object.<anonymous> (/Users/jdavies/getObj/getObj.js:144:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

Turns out that in the http-signature/lib/signer.js file that the 'passphrase' option is never checked for or propagated. Here is my hack that got this to work:

In signer.js:
At line 293 I inserted the following:
`assert.optionalString(options.passphrase, 'options.passphrase');`

At line 363 (formerly line 362) I modifed the line to the following to propagate the options object:
`key = sshpk.parsePrivateKey(options.key, 'auto', options);`

Obviously, hardcoding 'auto' for the format is not the correct approach, but it made the code work for me. Here is the command I used to generate my private key:
`openssl genrsa -out ~/oci_api_key.pem -aes128 2048 `

the openssl tool required me to provide a passphrase. When I later tried to use the http-signature module, I came across this issue. I hope this helps.

### PR DESCRIPTION
**Pull request by ArisuOngaku**
Fix #81 

Allow requests to be signed with a private key that is protected with a passphrase.

### CODE REVIEW

**Comment by jasonbking** [comment]
Can you run 'make check' -- it looks like there's a couple of minor formatting errors -- can you fix this and update the PR?

**Comment by ArisuOngaku** [comment]
There you go, fixed those.

However it looks like my `make check` couldn't complete because of missing dependencies (I don't have `json` in my path?):
```
$ make check

deps/javascriptlint/build/install/jsl --nologo --nosummary --conf=tools/jsl.node.conf lib/parser.js lib/signer.js lib/index.js lib/utils.js lib/verify.js
/r/arisu/dev/node-http-signature/lib/parser.js
/r/arisu/dev/node-http-signature/lib/signer.js
/r/arisu/dev/node-http-signature/lib/index.js
/r/arisu/dev/node-http-signature/lib/utils.js
/r/arisu/dev/node-http-signature/lib/verify.js
deps/jsstyle/jsstyle -f tools/jsstyle.conf lib/parser.js lib/signer.js lib/index.js lib/utils.js lib/verify.js
/bin/sh: json: command not found
version is:
[ "`cat package.json | json version`" = "`grep '^## ' CHANGES.md | head -2 | tail -1 | awk '{print $2}'`" ]
/bin/sh: json: command not found
make: *** [Makefile:32: check-version] Error 1
```

**Comment by jasonbking** [comment]
It looks like the two issues are:
```
17:51:35  lib/signer.js: 108: line > 80 characters
17:51:35  lib/signer.js: 350: line > 80 characters
```
The json utility is:
```
json@10.0.0 | Proprietary | deps: none | versions: 16
a 'json' command for massaging and processing JSON on the command line
https://github.com/trentm/json#readme

keywords: json, jsontool, filter, command, shell

bin: json

dist
.tarball: https://registry.npmjs.org/json/-/json-10.0.0.tgz
.shasum: c49a939d4abc7067cc225419d5dd17ab7bf2f66c
.integrity: sha512-iK7tAZtpoghibjdB1ncCWykeBMmke3JThUe+rnkD4qkZaglOIQ70Pw7r5UJ4lyUT+7gnw7ehmmLUHDuhqzQD+g==
.unpackedSize: 122.1 kB

maintainers:
- trentm <trentm@gmail.com>

dist-tags:
latest: 10.0.0

published a week ago by trentm <trentm@gmail.com>
```
(i.e. `npm install json`).

**Comment by ArisuOngaku** [comment]
Thanks for the help; since it is used by a dev tool I'd add it to dev dependencies and also add the `make check` as a `lint` script in `package.json` (I can make the PR if you want).

Anyway, the `make check` fully passes and there are no other problems.

**Review by jasonbking — APPROVED** [review]

**Comment by NigelNec** [comment]
Hello everyone,

When I download this package, I tried in 2 different projects, with "npm i http-signature@latest" the code from this PR is not included, the file "signer.js" is only 450 lines instead of 483.

My package.json indicates version 1.3.4

Am I doing something wrong?

Thanks in Advance,
Nigel

**Comment by ArisuOngaku** [comment]
@NigelNec this package simply didn't get a release since this PR was merged (yet).

check the [commit history](https://github.com/joyent/node-http-signature/commits/master)

**Comment by NigelNec** [comment]
Understood, I'll download the zip file for now.
Thanks for the help

**Comment by jasonbking** [comment]
I'll get a release cut and updated on npm. It'll probably be tomorrow when that happens.

**Pull request merged**
